services:
  db:
    image: mariadb:11
    container_name: pz_pablo_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "PabloLopez@2004"
      MARIADB_DATABASE: "ud_las_palmas_2026"
      MARIADB_USER: "usuarioPaLo"
      MARIADB_PASSWORD: "usuario@1"
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - pz_pablo_network

  web:
    image: plopezc03/actividad61-aplicacion-crud-php:latest
    container_name: pz_pablo_web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - pz_pablo_network

networks:
  pz_pablo_network:
    driver: bridge
